[phases.setup]
nixPkgs = ["nodejs", "nodejs.pkgs.npm"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "NODE_ENV=production npm start"

[env]
NODE_ENV = "production"
